### ISSUE TITLE
solr-operator image not found 0.1.1

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#11]
**Describe the bug**
In config/operators/solr_operator.yaml 

```
image: bloomberg/solr-operator:0.1.1
```
However I don't see this image on Docker Hub. Results in subsequent state...

```
    state:
      waiting:
        message: 'rpc error: code = Unknown desc = Error response from daemon: manifest
          for bloomberg/solr-operator:0.1.1 not found'
```

**To Reproduce**
Run the examples

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Operating System and Version: Docker for Mac Version 2.0.0.3 (31259) with K8s single node
