### ISSUE TITLE
Provide a spec to create solr cloud backup

### ISSUE THREAD

**Issue by krishnachalla-hv** [bloomberg/solr-operator#123]
**Is your feature request related to a problem? Please describe.**
Right now the documentation is having very minimal information about how backup solr cloud to persistent volume.
**Describe the solution you'd like**
Please provide kuernetes spec to back up solr cloud data with with at least some of the available options. Right now our company is planning to go production with this solr-operator but there is documentation regarding how mount the volume which is backed up earlier. If that option is available then solr cloud can be use the same data.

**Describe alternatives you've considered**
I have found no alternatives so far. If you suggest any work around I can at lease implement that.

**Comment by HoustonPutman** [comment]
Hello @krishnachalla-hv ,

If I understand correctly, you have used the SolrBackup CRD to take backups of your Solr data and now you want to be able to restore from those backups? If so that functionality has unfortunately not been built into the operator yet.

If you just want better examples/documentation around creating backups then that is an easier thing to address in the short term. If the backup isn't working for you right now, it might be because your cloud is not using a `ReadWriteMany` volume for it's `Spec.backupRestoreVolume`. Solr requires shared storage to be able to take backups, thus you will need a separate `ReadWriteMany` volume to act as that shared storage.

**Comment by krishnachalla-hv** [comment]
Hi @HoustonPutman , thank you for the awesome sole-operator. May I know when the solr backup restore option will be available in the Solr Backup CRD? Is there any work around to restore the backup to Solr Cloud from official Solr REST API?

**Comment by HoustonPutman** [comment]
Hello @krishnachalla-hv , so sorry for the delay.

I'm not sure anyone is currently working on the functionality for restoring Solr. Contributions are always welcome though!

And as for documentation on the S3 endpoint, there is no yaml example, but you can find the API here: https://github.com/bloomberg/solr-operator/blob/master/api/v1beta1/solrbackup_types.go#L79
If you provide values for all of those then it should work.

Something like:

```yaml
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrBackup
metadata:
  name: solrbackup-test
  namespace: default
spec:
  persistence:
    S3:
      endpointUrl: "s3-endpoint-url.com"
      bucket: "solr-backup"
      secrets:
        fromSecret: <your secret>
        ...
  solrCloud: example
  collections:
    - example
```

For the `secrets` section you have to provide your own Kubernetes secret and the key names from the Kube Secret: https://github.com/bloomberg/solr-operator/blob/master/api/v1beta1/solrbackup_types.go#L130

If you are trying to manually do restores, it will be much easier to use the volumes than S3 though.
