### ISSUE TITLE
Optional User provided InitContainer

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#157]
**Is your feature request related to a problem? Please describe.**
Provide an optional interface for a user to request an InitContainer to run commands in SolrCloud pod. Our use case is to use an Init container to warmup filesystem cache in SolrCloud memory, prior to allowing real traffic to hit the SolrCloud pod.

https://godoc.org/k8s.io/api/core/v1#PodSpec

**Describe the solution you'd like**
```
spec:
  customSolrKubeOptions:
    additionalInitContainers:
      - name: warm-up
         image: "library/busybox:latest"
         command: [ "bash", "warmup.sh" ]
```
    

**Describe alternatives you've considered**
Adding a Docker entry point for a custom solrcloud image that can run warmup.
