### ISSUE TITLE
Support creating Standard Collection Aliases

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#48]
**Is your feature request related to a problem? Please describe.**
CREATEALIAS registers the alias name with the names of one or more collections provided by the command.

Probably do this via a new CRD, "SolrCollectionAlias"

**Describe the solution you'd like**

```
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCollectionAlias
metadata:
  name: collection-alias-foo
spec:
  solrCloud: example
  collections:
    - example
    - example2
  aliasType: standard
```
