### ISSUE TITLE
The current example/test_solrprometheusexporter.yaml doesn't work

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#50]
**Describe the bug**
The current example/test_solrprometheusexporter.yaml doesn't work. The spec reference (https://github.com/bloomberg/solr-operator/blob/master/example/test_solrprometheusexporter.yaml#L10) doesn't exist in types. Also, from within the cluster the ingress doesn't connect. 

```
solr@solrprometheusexporter-sample-solr-metrics-686b9df785-5kjwt:/opt/solr-8.2.0$ curl http://default-example-solrcloud-0.ing.local.domain:80/solr
curl: (7) Failed to connect to default-example-solrcloud-0.ing.local.domain port 80: Connection refused
```

I suggest we switch the example over to using the service endpoint. Seems like this is the more reasonable way for a pod to talk to a service within the cluster anyways.

**Additional context**
Perhaps update example/test_solrprometheusexporter.yaml to:

```
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrPrometheusExporter
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: solrprometheusexporter-example
spec:
  solrReference:
    standalone:
      address: "http://example-solrcloud-common.default/solr"
  image:
    tag: 8.2.0
```

Open to other ideas here. I can create a PR once we get to kubebuilder v2 done based upon feedback here.
