### ISSUE TITLE
Make solr references in the Collection & Alias CRDs more flexible.

### ISSUE THREAD

**Issue by HoustonPutman** [bloomberg/solr-operator#58]
Right now both accept a cloud in the form of a string. This is meant to be the name of a solrCloud resource in the same namespace as the collection/alias resource referencing it.

We should make these more flexible, like the PrometheusExporter CRD.

So something like:

```yaml
spec:
  solr:
    kubeSolr:
      name: test
      namespace: test
    cloudUrl: test.com:8983/solr
    zkConnectionInformation:
      connectionString: test1:2181,test2:2181
      chRoot: /test
```

All of these options would be optional, and would have defaults. But one of `kubeSolr`, `cloudUrl` or `zkConnectionInformation` (names not set in stone) would have to be specified.
