### ISSUE TITLE
Ability to request custom template annoations for StatefulSet of SolrCloud

### ISSUE THREAD

**Issue by sepulworld** [bloomberg/solr-operator#63]
**Is your feature request related to a problem? Please describe.**
We would like to apply kube2iam roles to pods in solrcloud statefulset. The role will allow access to s3 for backups. 

Snippet of what is needed
```
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: role-arn
```

**Describe the solution you'd like**

The ability to add any spec/template/metadata annotation for developers to request
