### ISSUE TITLE
connection refused while creating a solr_collection

### ISSUE THREAD

**Issue by aberfeldy** [bloomberg/solr-operator#71]
**Describe the bug**
On creating a solr collection via this crd:
```yaml
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCollection
metadata:
  name: escenic
  namespace: solr
spec:
  solrCloud: escenic
  collection: escenic
  routerName: compositeId
  routerField: id
  autoAddReplicas: true
  numShards: 5
  replicationFactor: 2
  maxShardsPerNode: 1
  collectionConfigName: escenic
```
I'm getting an error: 
```json
{
	"namespace": "solr",
	"cloud": "escenic",
	"collection": "escenic",
	"error": "Recieved bad response code of 400 from solr with response: {\"responseHeader\":{\"status\":400,\"QTime\":3},\"error\":{\"metadata\":[\"error-class\",\"org.apache.solr.common.SolrException\",\"root-error-class\",\"org.apache.solr.common.SolrException\"],\"msg\":\"Collection: escenic not found\",\"code\":400}}\n"
}
```
This happens because it tries to call solr by the headless service ("$(POD_HOSTNAME)." + solrCloud.HeadlessServiceName()) which is not available in the cluster.
In this case the call to `http://escenic-solrcloud-3.escenic-solrcloud-headless:80/solr` gets a connection refused, while the call to `http://escenic-solrcloud-3.sorl:80/solr` (the none-headless service) is completly fine.

**To Reproduce**
1. followed the tutorial in the readme until creation of a solr_collection

**Expected behavior**
To see the collection be created or to use at least services that exist. Maybe I'm missing some step to create the expected services. Or it should be possible to to use the existing svc (pod-hostnema.namespace) instead, but when I change that in the yaml, it gets immediately reverted to "$(POD_HOSTNAME)." + solrCloud.HeadlessServiceName() (which is good, but doesn't work for me) 

**Environment (please complete the following information):**
 - Kubernetes 15.9
