### ISSUE TITLE
Invalid router field is set on collection if none is specified in solrcollection yaml file

### ISSUE THREAD

**Issue by timterle** [bloomberg/solr-operator#97]
**Describe the bug**
When creating a collection and not specifying routerField it's set to the empty string which prevents anything from being indexed.

**To Reproduce**

```
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCollection
metadata:
  name: example-col
spec:
  solrCloud: example
  collection: example-col
  routerName: compositeId
  autoAddReplicas: false
  numShards: 1
  replicationFactor: 1
  maxShardsPerNode: 1
```
If I apply the above config I will not be able to index anything in the collection as router.field will be set to empty string and Solr will throw "SolrException: No value for :. Unable to identify shard"

**Expected behavior**
router.field should not be set at all if it's missing in the config
